Fix bug for old Yahoo! profiles
If the user who was trying to authenticate hasn't activated the Yahoo Profile (ie, has an old/unused Yahoo account), the Authomatic.user.update() method was returning an error (probably because old profiles doesn't have location data):

    File "../lib/python2.7/site-packages/authomatic/providers/oauth1.py", line 785, in _x_user_parser
        user.city, user.country = _user.get('location', ',').split(',')
    ValueError: need more than 1 value to unpack

I fix the bug with a try/exception clause to avoid impeding the authentication due to the lack of a comma in the location info Yahoo was sending.